# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=100)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('archivado', models.BooleanField(default=False)),
            ],
        ),
    ]
